name: Build
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  windows:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [Win32, x64]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - run: cmake -S . -B build -A ${{ matrix.arch }}
      - run: cmake --build build --config Release
      - run: ctest --test-dir build -C Release --output-on-failure
      - run: cmake --install build --config Release --prefix package
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: AardvarkUI-${{ matrix.arch }}
          if-no-files-found: error
          path: |
            package/
            build/Release/aardvark_ui_demo.exe
